INSERT INTO USERS(ID, NAME, BIRTH_DATE) VALUES (10001, 'Ranga', current_date());
INSERT INTO USERS(ID, NAME, BIRTH_DATE) VALUES (10002, 'Alberto', current_date());
INSERT INTO USERS(ID, NAME, BIRTH_DATE) VALUES (10003, 'Ravi', current_date());

INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (2001, 'I WANT TO LEARN AWS', 10001);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (2002, 'I WANT TO LEARN JAVA', 10001);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (2003, 'I WANT TO LEARN NODE', 10002);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (2004, 'I WANT TO LEARN SQL', 10003);